tags:
- llvm
- pipeline
- ascent
- nocuda

spack:
  specs:
    - magma cuda_arch=70

    # MISC
    - openpmd-api
    - slate
    - stc

    # XSDK
    - py-libensemble^python@3.7.3
    - flecsi+cinch
    - hypre
    - mfem
    - trilinos@12.14.1+dtk+intrepid2+shards
    - sundials
    - petsc ^superlu-dist@6.3.0
    - strumpack
    - superlu-dist
    - superlu
    - tasmanian

    # DATA MANAGEMENT, IO, CHECKPOINT RESTART
    - faodel
    - mercury
    - hdf5
    - adios2
    - adios
    - darshan-runtime
    - darshan-util
    - veloc
    - scr
    - parallel-netcdf
    - unifyfs

    # PMR CORE
    - qthreads
    - papyrus@develop
    - bolt
    - raja
    - upcxx
    - aml
    - kokkos+openmp
    - openmpi
    - umpire
    - libquo
    - globalarrays
    - turbine # provides swift/t runtime

    # TOOLS AND TECHNOLOGY
    - pdt  
  #- py-ytopt^python@3.7.3 #provides surf
    - tau
    - hpctoolkit
    - dyninst
    - gotcha
    - caliper
    - papi
    - py-jupyterhub

    # VIS + REDUCTION
  #- catalyst
    - zfp
    - sz
  #- paraview+mpi+qt ^llvm~all_targets~clang~compiler-rt~internal_unwind~libcxx+link_dylib~lld~lldb~omp_tsan~polly~python ^mesa ^qt@5.10.0

    # COMPILERS + SUPPORT
  #- llvm-openmp
  #- nrm^python@3.7.3
  
  # Ecosystem
    - libnrm
  #- geopm^py-numpy@1.16.5^py-pandas@0.24.2
    - mpifileutils@develop~xattr
    - rempi
    - ninja
    - kokkos-kernels

  packages:
    all:
      variants: +mpi
      providers:
        mpi: [mpich]
        blas: [openblas]
    gcc:
      variants: +strip
    mpich:
      version: [3.2.1]
      variants: ~wrapperrpath
    binutils:
      version: [2.33.1]
      variants: +gold+headers+libiberty~nls
    py-ipython:
      version: [7.3.0]

  view: false
  concretization: separately

nocuda:
  exclude:
    specs:
      - magma cuda_arch=70
      - slate

ppc64le:
  exclude:
    specs:
    - slate
    - stc
    - faodel
  overwrite:
    packages:
      libffi:
        version: [3.2.1]
    specs:
    - faodel~tcmalloc

llvm:
  exclude:
    specs:
    - hpctoolkit
    - dyninst
  overwrite:
    specs:
    - hpctoolkit ^elfutils%gcc@7.3.0
    - dyninst ^elfutils%gcc@7.3.0
    packages:
      all:
        compiler: [clang@9.0.1]
      clang:
        version: [9.0.1]

pipeline:
  overwrite:
    config:
      install_tree: /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation
      build_jobs: 8

ascent:
  overwrite:
    packages:
      all:
        providers:
          mpi:
          - spectrum-mpi@10.3.1.2
      cuda:
        buildable: false
        version: [cuda/10.1.243]
        modules:
          cuda@10.1.105: cuda/10.1.243
      spectrum-mpi:
        buildable: false
        version: [10.3.1.2]
        modules:
          spectrum-mpi@10.3.1.2: spectrum-mpi/10.3.1.2-20200121
    config:
      misc_cache: $spack/cache
      install_tree: $spack/$padding:512
